# Generated by Django 5.0.4 on 2024-06-20 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                ("keyword_id", models.AutoField(primary_key=True, serialize=False)),
                ("keyword", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Administrator", "Administrator"),
                            ("Tutor", "Tutor"),
                            ("Student", "Student"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                ("article_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("born", models.DateField(blank=True, null=True)),
                ("died", models.DateField(blank=True, null=True)),
                ("nationality", models.CharField(blank=True, max_length=50, null=True)),
                ("known_for", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "notable_work",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("about", models.TextField(blank=True, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("medium", models.CharField(blank=True, max_length=255, null=True)),
                ("dimensions", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "designed_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("developer", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subjects.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArticleKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subjects.article",
                    ),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subjects.keyword",
                    ),
                ),
            ],
            options={
                "unique_together": {("article", "keyword")},
            },
        ),
    ]
