# Generated by Django 5.0.4 on 2024-06-26 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        # migrations.AlterModelTable(
        #     name='article',
        #     table='Articles',
        # ),
        # migrations.AlterModelTable(
        #     name='articlekeyword',
        #     table='ArticleKeywords',
        # ),
        # migrations.AlterModelTable(
        #     name='category',
        #     table='Categories',
        # ),
        # migrations.AlterModelTable(
        #     name='keyword',
        #     table='Keywords',
        # ),
        # migrations.AlterModelTable(
        #     name='user',
        #     table='Users',
        # ),
    ]
