# Generated by Django 4.2.13 on 2024-06-28 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_article_table_alter_articlekeyword_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='Articles',
        ),
        migrations.AlterModelTable(
            name='articlekeyword',
            table='ArticleKeywords',
        ),
        migrations.AlterModelTable(
            name='category',
            table='Categories',
        ),
        migrations.AlterModelTable(
            name='keyword',
            table='Keywords',
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
